# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3ba92d1becb34834be7253e978154dbbbe0066cf290e1026e7d92f02515a53107ebc2dfa8a420604f525b6b78bd7a4af01e58011eb76b89377be9e6122a131

test:
  secret_key_base: bf6a6ec5b874756f18fdbfb7640e721152a8294bce2a02100671c52dd5fd13b7de25aa6a3272954c9421a3c1e52793176913a43a376f690849c89a7726d3004e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
